name: RediX CI

on:
  push:
    branches:
      - 'feature/**'
      - 'test/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make
      - name: Build
        run: |
          mkdir -p build/${{ matrix.build-type }}
          cd build/${{ matrix.build-type }}
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ../..
          make -j$(nproc)
      - name: Run Tests
        run: |
          cd build/Debug
          ctest --output-on-failure
